version: '3.7'

services:
  geolocalization.api:
    image: guilhermesampaio/easynovation-goals-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 8000:80
  mongo.db:
    image: mongo    
    ports:
      - "27017:27017"